-- Core mapping table: short code -> long URL. Postgres is the source of truth.
CREATE TABLE links (
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    short_code             VARCHAR(32)  NOT NULL,
    long_url               TEXT         NOT NULL,
    -- SHA-256 (hex) of the per-link management token. The plaintext token is returned to
    -- the creator exactly once and never stored. Used to authorize destructive operations.
    management_token_hash  VARCHAR(64)  NOT NULL,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- NULL = never expires. When set and in the past, the link resolves to 410 Gone.
    expires_at             TIMESTAMPTZ  NULL,
    CONSTRAINT links_pkey PRIMARY KEY (id)
);

-- The short code is the public identifier and must be globally unique. This unique
-- constraint is the *single arbiter* of collisions and custom-alias races: the application
-- never does check-then-insert; it inserts and lets the database reject duplicates.
CREATE UNIQUE INDEX ux_links_short_code ON links (short_code);

-- Supports efficient expiry sweeps / filtering without scanning the whole table.
CREATE INDEX ix_links_expires_at ON links (expires_at) WHERE expires_at IS NOT NULL;
