-- Per-click analytics events. Keyed by short_code (not link id) on purpose: clicks are recorded
-- on the redirect hot path, which may be served entirely from the Redis cache without loading the
-- link row. Decoupling from links.id lets capture work on the cache-hit path.
--
-- Privacy: ip_hash is HMAC-SHA256(ip, server-salt); the raw IP is never stored (see risk R8).
CREATE TABLE click_events (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    short_code   VARCHAR(32)  NOT NULL,
    occurred_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ip_hash      VARCHAR(64),
    user_agent   VARCHAR(512),
    referer      VARCHAR(2048),
    CONSTRAINT click_events_pkey PRIMARY KEY (id)
);

-- Aggregations filter by code and group/scan by time; this composite index serves both.
CREATE INDEX ix_click_events_code_time ON click_events (short_code, occurred_at);
